### ISSUE TITLE
Incompatible with Pester 5.0. Error in diskcapacity check. 'Assert-DiskSpace' is unknown

### ISSUE THREAD

**Issue by laric** [sqlcollaborative/dbachecks#775] opened 2020-06-15 12:08 UTC
### General Troubleshooting steps
- [x] Verified running the latest release of dbachecks? 
V2.0.3
Does `(Find-Module dbachecks).Version match (Get-Module dbachecks).Version.ToString()`
yes
![image](https://user-images.githubusercontent.com/6729780/37113488-60e5e172-21fa-11e8-8115-814edfbfabb6.png)

- [x] Can duplicate in new/clean PowerShell session (clean = `powershell -NoProfile`)?
yes
### Version Information
 - Operating System (Name|Version):  Windows Server 2016
 - PowerShell Version:  5.1
 - SQL Server (Edition|Version): 
2017
### Steps to Reproduce
<--  
  PLEASE include as much information as possible if this is a bug report.
  The more you include the faster we can identify the problem and get it fixed
-->
 - [x] Attach output from PowerShell console (if possible/allowed)
Invoke-DbcCheck -Check diskcapacity -ComputerName xXxXxX
### Description of Bug
Starting discovery in 1 files.
Discovery finished in 2.09s.
[-] Disk Space.Testing Disk Space on xXxXxX.D:\ with 64.49% free should be at least 20% free on xXxXxX 386ms (254ms|133ms)
 CommandNotFoundException: The term 'Assert-DiskSpace' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
 at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\dbachecks\2.0.3\checks\Server.Tests.ps1:36
[-] Disk Space.Testing Disk Space on xXxXxX.K:\ with 83.28% free should be at least 20% free on xXxXxX 41ms (39ms|2ms)
 CommandNotFoundException: The term 'Assert-DiskSpace' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
<--  
  PLEASE include as much information as possible if this is a bug
Explain what it does that you would like it not to do
or
What it doesnt do that you would like it to do :-)
-->

**Comment by jeff-edmunds** [comment] 2020-06-22 18:28
@laric I encountered this same problem when I tried installing dbachecks for the first time last week. I got some help from someone in the Slack channel... I believe the issue is with the Pester module.  When you run the command to install dbachecks, it installs all of the dependent modules, including the most recent version of Pester.  I had to remove Pester and reinstall it, limiting the version to 4.10.1.  This error (and several others I was getting) all went away.

**Comment by laric** [comment] 2020-06-22 18:29
I will give it a go.

**Comment by laric** [comment] 2020-06-22 18:46
That works fine if you force uninstall of pester 5. But this leaves this still as a bug. Not compatible with pester 5.

**Comment by jeff-edmunds** [comment] 2020-06-22 20:00
Agreed. I think this is the same issue reported in 774.
Duplicate of #774

**Closed** 2020-09-22 12:08 UTC
