### ISSUE TITLE
Skip 'Default Backup Compression' for 2005 and under versions

### ISSUE THREAD

**Issue by LowlyDBA** [sqlcollaborative/dbachecks#441] opened 2018-04-09 19:23 UTC
## Issue

Check doesn't account for < SQL 2008 not having this as an instance-level option. 

## Additional information    
Suggested modification to skip SQL versions 2005 and under (can open as PR if people agree with the change/approach): 

```powershell
Describe "Default Backup Compression" -Tags DefaultBackupCompression, $filename {
    $defaultbackupcompression = Get-DbcConfigValue policy.backup.defaultbackupcompression
    @(Get-Instance).ForEach{ 
        Context "Testing Default Backup Compression on $psitem" {
            It "Default Backup Compression is set to $defaultbackupcompression on $psitem" -Skip(Connect-DbaInstance -SqlInstance $psitem | Select-Object -ExpandProperty "Version" | Select-Object -ExpandProperty "Major" -lt 10) {
                (Get-DbaSpConfigure -SqlInstance $psitem -ConfigName "DefaultBackupCompression").ConfiguredValue -eq 1 | Should -Be $defaultbackupcompression -Because "The default backup compression should be set correctly"
```

**Comment by SQLDBAWithABeard** [comment] 2018-04-27 12:35
@nohwnd - If you have time would you mind looking at 
https://github.com/sqlcollaborative/dbachecks/blob/backupcompression/tests/checks/InstanceChecks.Tests.ps1#L33

I am trying to write a test to ensure that a test is skipped when a sql version is below 10.
But when I run the uncommented code I get

[-] Should not run for SQL 2005 and below 680ms
        RuntimeException: You did not declare a mock of the b9d10fa6-db0e-49c2-83d1-b14135023c57 Command.
        at <ScriptBlock>, C:\Users\mrrob\OneDrive\Documents\GitHub\dbachecks\tests\checks\InstanceChecks.Tests.ps1: line 46

or cannot find command Get-Version if I dont declare it in the test

**Comment by SQLDBAWithABeard** [comment] 2018-04-27 15:42
Hmm - See screenshot - Clean session - import module - run test

![image](https://user-images.githubusercontent.com/6729780/39371579-04862afa-4a3a-11e8-81c6-c3bc7ae4b654.png)

**Comment by SQLDBAWithABeard** [comment] 2018-04-27 15:44
and if I declare the function in the test

![image](https://user-images.githubusercontent.com/6729780/39371639-2e6f1b7e-4a3a-11e8-9aef-e53097b5b802.png)

**Comment by nohwnd** [comment] 2018-04-28 09:00
Okay so the problem is that when you `Invoke-Pester` inside of `Describe` the Pester state gets overwritten and so you get an error. I tried replicating with simply executing Invoke-Pester over a non-existing file in a describe, and I get a different error (Mock is not in mock table). So you must me doing something else as well (probably setting up a mock for the same command inside of the test or something.) I don't think there is any good solution for this at the moment, testing the framework inside of the framework is difficult. And we are using sepeare jobs for that, but consuming the results is not ideal, still it's the only way to go unless we externalize the state of Pester.

**Comment by SQLDBAWithABeard** [comment] 2018-05-09 12:35
merged

**Closed by SQLDBAWithABeard** 2018-05-09 12:35 UTC
